spring.application.name=fidebiblio

# Conexion a base de datos Aiven 
spring.datasource.url=jdbc:mysql://mysql-3fd094c3-chrisbc97-a950.k.aivencloud.com:25996/fidebiblio?sslMode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_KZtepKKJSQs384yTXln
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

server.port=8080


spring.thymeleaf.cache=false

#  Firebase Storage 
firebase.bucket.name=fidebiblio.firebasestorage.app
firebase.storage.path=fidebiblio
firebase.json.path=firebase
firebase.json.file=fidebiblio-firebase-adminsdk-fbsvc-36083ecd33.json